export const metadata = {
  title: {
    default: 'Default title',
    template: '%s | template'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>Header</header>
        <div>{children}</div>
        <footer>Footer</footer>
      </body>
    </html>
  )
}
